# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

version: 2
updates:
  - package-ecosystem: nuget
    directory: Application/
    target-branch: main
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /Application/EdFi.Ods.AdminApi.DBTests
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /Application/EdFi.Ods.AdminApi.UnitTests
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /Application/EdFi.Ods.AdminApi
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /Docker/Settings/DB-Admin/mssql
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /Docker/Settings/DB-Admin/pgsql
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /Docker/Settings/gateway
    schedule:
      interval: daily
